# Generated by Django 2.2.12 on 2020-05-18 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_load_initial_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="customtext",
            name="hghgh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
