# Generated by Django 2.2.12 on 2020-05-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customtext_hghgh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customtext',
            name='hghgh',
        ),
    ]
