# Generated by Django 2.2.12 on 2020-05-18 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_remove_customtext_hghgh"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fdghfghfhg",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nbhghg", models.BigIntegerField()),
            ],
        ),
    ]
